apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff
  template:
    metadata:
      labels:
        app: staff
    spec:
      containers:
      - name: staff
        image: pragnesh8122001/staff-services:latest
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: staff-services
spec:
  selector:
    app: staff
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
